version: '2'

services:
  php:
    container_name: simiweb-frontend_php
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - $NGINX_PUBLIC_PORT:80
    depends_on:
      - simiweb_db
    networks:
      simiwebnetwork:
        ipv4_address: 192.168.0.6

  simiweb_db:
    container_name: simiweb-frontend_db
    image: "postgres:latest"
    ports:
      - $DB_PUBLIC_PORT:$DB_INNER_PORT
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
      PGDATA: "/data/postgres"
      TZ: 'Antarctica/Vostok'
    networks:
      simiwebnetwork:
        ipv4_address: 192.168.0.5


networks:
    simiwebnetwork:
      external: true

volumes:
  db-data: