--
-- PostgreSQL database dump
--

-- Dumped from database version 14.4 (Debian 14.4-1.pgdg110+1)
-- Dumped by pg_dump version 14.5 (Ubuntu 14.5-1.pgdg20.04+1)

-- Started on 2022-10-18 16:11:46 MSK

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3660 (class 0 OID 23001)
-- Dependencies: 246
-- Data for Name: products_spr; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (1, '1010040', '0200', '0200-RSEV', 'DR-0211', 'Руда сульфидная Cu-Ni АО "КГМК"', 'Руда сульфидная Cu-Ni АО "КГМК"', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (2, '1010001', '0200', '0200-MECO', 'RF-0210', 'Файнштейн Cu-Ni ПАО "ГМК "НН"', 'Файнштейн Cu-Ni ПАО "ГМК "НН"', NULL, NULL, 'R', 'нет', NULL, NULL, 'Сырье ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (3, '1010101', '0200', '0200-MECO', 'RF-0210', 'RF Концентрат никелевый', 'RF Концентрат никелевый', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (4, '1010103', '0200', '0200-MECO', 'RF-0210', 'RF Штейн никелевый', 'RF Штейн никелевый', '0210', 'RF', 'R', 'да', 'нет', NULL, 'Готовая продукция', 'Общий', 1, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (5, '1010105', '0200', '0200-MECO', 'RF-0210', 'RF Файнштейн никелевый', 'RF Файнштейн никелевый', '0210', 'RF', 'R', 'да', 'нет', NULL, 'Готовая продукция', 'Общий', 1, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (6, '1010106', '0200', '0200-MECO', 'RF-0210', 'RF Штейн медный', 'RF Штейн медный', '0210', 'RF', 'R', 'да', 'нет', NULL, 'Готовая продукция', 'КГМК', 1, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (7, '1010121', '0200', '0200-MECO', 'OK-0210', 'OK Аноды никелевые', 'OK Аноды никелевые', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (8, '1010122', '0200', '0200-MECO', 'OK-0210', 'OK ПНТП', 'OK ПНТП', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (9, '1010123', '0200', '0200-MECO', 'OK-0210', 'OK Гранулы никелевые', 'OK Гранулы никелевые', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (10, '1010127', '0200', '0200-MECO', 'OK-0210', 'OK Шлак анодный никелевый', 'OK Шлак анодный никелевый', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы площадок', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (11, '1010132', '0200', '0200-MECO', 'OK-0210', 'OK Немагнитная фракция ПНТП', 'OK Немагнитная фракция ПНТП', NULL, NULL, 'R', 'нет', NULL, NULL, 'N', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (12, '1010153', '0200', '0200-MECO', 'E1-0210', 'E1 Концентрат кобальтовый', 'E1 Концентрат кобальтовый', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (13, '1010154', '0200', '0200-MECO', 'E1-0210', 'E1 Шлам никелевый', 'E1 Шлам никелевый', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (14, '1010155', '0200', '0200-MECO', 'E1-0210', 'E1 Скрап анодный никелевый', 'E1 Скрап анодный никелевый', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы собственные ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (15, '1010160', '0200', '0200-MECO', 'E1-0210', 'E1 Осыпь никелевая', 'E1 Осыпь никелевая', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы собственные ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (16, '1010161', '0200', '0200-MECO', 'E1-0210', 'E1 Медь цементная', 'E1 Медь цементная', NULL, NULL, 'R', 'нет', NULL, NULL, 'Возвратные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (17, '1010182', '0200', '0200-MECO', 'E2-0210', 'E2 Кек кобальтовый первичный', 'E2 Кек кобальтовый первичный', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (18, '1010185', '0200', '0200-MECO', 'E2-0210', 'E2 Остаток хлорного выщелачивания', 'E2 Остаток хлорного выщелачивания', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (19, '1010187', '0200', '0200-MECO', 'E2-0210', 'E2 Зачистки Ni (сметки)', 'E2 Зачистки Ni (сметки)', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы собственные ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (20, '1010188', '0200', '0200-MECO', 'E2-0210', 'E2 Зачистки Ni (ЭО)', 'E2 Зачистки Ni (ЭО)', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы собственные ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (21, '1010189', '0200', '0200-MECO', 'E2-0210', 'E2 Зачистки Ni (зачистки фильтр-пресса)', 'E2 Зачистки Ni (зачистки фильтр-пресса)', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы собственные ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (22, '1010190', '0200', '0200-MECO', 'E2-0210', 'E2 Остаток выщелачивания', 'E2 Остаток выщелачивания', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы собственные ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (23, '1010192', '0200', '0200-MECO', 'E2-0210', 'E2 Раствор хлорного растворения', 'E2 Раствор хлорного растворения', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы собственные', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (24, '1010193', '0200', '0200-MECO', 'E2-0210', 'E2 Медь цементная', 'E2 Медь цементная', NULL, NULL, 'R', 'нет', NULL, NULL, 'Возвратные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (25, '1010212', '0200', '0200-MECO', 'NC-0210', 'NC Огарок обжига остатков синтеза', 'NC Огарок обжига остатков синтеза', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы собственные', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (26, '1010214', '0200', '0200-MECO', 'NC-0210', 'NC Зачистки оборудования ОКН (корки)', 'NC Зачистки оборудования ОКН (корки)', NULL, NULL, 'R', 'нет', NULL, NULL, 'собственные ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (27, '1010216', '0200', '0200-MECO', 'NC-0210', 'NC Окатыши остатков дожигания', 'NC Окатыши остатков дожигания', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы площадок ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (28, '1010235', '0200', '0200-MECO', 'CO-0210', 'CO Медь цементная', 'CO Медь цементная', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы \nсобственные \n', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (29, '1010236', '0200', '0200-MECO', 'CO-0210', 'CO Рафинат 3', 'CO Рафинат 3', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы \nсобственные ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (30, '1010334', '0200', '0200-MECO', 'KP-0210', 'KP Выломки ГМО', 'KP Выломки ГМО', NULL, NULL, 'R', 'нет', NULL, NULL, 'Возвратные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (31, '1010335', '0200', '0200-MECO', 'KP-0210', 'KP Выломки ЭПО', 'KP Выломки ЭПО', NULL, NULL, 'R', 'нет', NULL, NULL, 'Возвратные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (32, '1010336', '0200', '0200-MECO', 'KP-0210', 'KP Шлак металлургический', 'KP Шлак металлургический', NULL, NULL, 'R', 'нет', NULL, NULL, 'Возвратные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (33, '1010133', '0200', '0200-MECO', 'OK-0210', 'OK Пыль РЦ', 'OK Пыль РЦ', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы \nсобственные \n', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (34, '1010041', '0200', '0200-OBCO', 'OR-0211', 'OR  концентрат Cu-Ni', 'OR  концентрат Cu-Ni', '0211', 'OR', 'R', 'да', 'нет', NULL, 'Готовая продукция', 'Общий', 0.7, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (35, '1010042', '0200', '0200-OBCO', 'OR-0211', 'OR Отвальные хвосты', 'OR Отвальные хвосты', NULL, NULL, 'R', 'нет', NULL, NULL, 'Отвальные продукты', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (36, '1010151', '0200', '0200-MECO', 'E1-0210', 'E1 Никель первичный', 'E1 Никель первичный', '0210', 'E1', 'R', 'да', 'да', 'Ni', 'Готовая продукция', 'Общий', 1, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (37, '1010164', '0200', '0200-MECO', 'E1-0210', 'E1 Кек железистый отвальный', 'E1 Кек железистый отвальный', NULL, NULL, 'R', 'нет', NULL, NULL, 'Отвальные продукты', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (38, '1010181', '0200', '0200-MECO', 'E2-0210', 'E2 Никель первичный', 'E2 Никель первичный', '0210', 'E2', 'R', 'да', 'да', 'Ni', 'Готовая продукция', 'Общий', 1, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (39, '1010202', '0200', '0200-MECO', 'E2-0210', 'E2 Зачистки Ni (ОРиД)', 'E2 Зачистки Ni (ОРиД)', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы \nсобственные \n', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (40, '1010196', '0200', '0200-MECO', 'E2-0210', 'E2 Кек железистый отвальный', 'E2 Кек железистый отвальный', NULL, NULL, 'R', 'нет', NULL, NULL, 'Отвальные продукты', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (41, '1010231', '0200', '0200-MECO', 'CO-0210', 'CO Кобальт электролитный (товарный)', 'CO Кобальт электролитный (товарный)', '0210', 'CO', 'R', 'да', 'да', 'Co', 'Попутная продукция', 'Общий', 1, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (42, '1010211', '0200', '0200-MECO', 'NC-0210', 'NC Карбонильная никелевая продукция', 'NC Карбонильная никелевая продукция', '0210', 'NC', 'R', 'да', 'да', 'Ni', 'Готовая продукция', 'Общий', 1, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (43, '1010391', '0200', '0200-MECO', 'FM-0210', 'FM Продукт пенный ОХВ', 'FM Продукт пенный ОХВ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (44, '1010392', '0200', '0200-MECO', 'FM-0210', 'FM Продукт камерный ОХВ', 'FM Продукт камерный ОХВ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (45, '1010337', '0200', '0200-MECO', 'KP-0210', 'KP Раствор осветленный ', 'KP Раствор осветленный ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (46, '1010342', '0200', '0200-MECO', 'KP-0210', 'KP Сплав гранулированный', 'KP Сплав гранулированный', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (47, '1010339', '0200', '0200-MECO', 'KP-0210', 'KP Продукт камерный ОХВ подсушенный', 'KP Продукт камерный ОХВ подсушенный', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (48, '1010344', '0200', '0200-MECO', 'KP-0210', 'KP Выломки ЭПО УПОХР', 'KP Выломки ЭПО УПОХР', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (49, '1010253', '0200', '0200-MECO', 'AM-0210', 'АМ Медь цементная', 'АМ Медь цементная', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (50, '1010256', '0200', '0200-MECO', 'AM-0210', 'AM Выломки металлургических агрегатов', 'AM Выломки металлургических агрегатов', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (51, '1010331', '0200', '0200-MECO', 'KP-0210', 'KP Концентраты ДМ (КПП,КМСП,КСП)', 'KP Концентраты ДМ (КПП,КМСП,КСП)', '0210', 'KP', 'R', 'да', 'нет', NULL, 'Товарные полуфабрикаты', 'Общий', 1, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (52, '1013045', '0101', '0101-RTAI', 'DR-109W', 'Руда богатая р. Таймырский', 'Руда богатая р.Таймырский', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (53, '1013050', '0101', '0101-RKOM', 'DR-113W', 'Руда медистая ш. Комсомольская', 'Руда медистая р.Комсомольский', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (54, '1013044', '0101', '0101-RKOM', 'DR-113W', 'Руда богатая р. Комсомольский', 'Руда богатая р.Комсомольский', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (55, '421490', '0101', '0101-TOF0', 'TO-104W', 'Хвосты отвальные породные', 'Хвосты отвальные на закладку', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (56, '1013047', '0101', '0101-RMAY', 'DR-114W', 'Руда вкрапленная р. Маяк', 'Руда вкрапленная р.Маяк', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (57, '1013042', '0101', '0101-RMAY', 'DR-114W', 'Руда богатая р. Маяк', 'Руда богатая р.Маяк', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (58, '1013051', '0101', '0101-ROKT', 'DR-110W', 'Руда медистая р. Октябрьский', 'Руда медистая р.Октябрьский', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (59, '1013049', '0101', '0101-ROKT', 'DR-110W', 'Руда вкрапленная р. Октябрьский', 'Руда вкрапленная р.Октябрьский', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (60, '1013046', '0101', '0101-ROKT', 'DR-110W', 'Руда богатая р. Октябрьский', 'Руда богатая р.Октябрьский', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (61, '1013043', '0101', '0101-RSKL', 'DR-133W', 'Руда богатая ш. "Скалистая"', 'Руда богатая р.Скалистый', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (62, '1013055', '0101', '0101-TOF0', 'TO-104W', 'Концентрат медный ТОФ', 'Концентрат медный ТОФ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (63, '1013057', '0101', '0101-TOF0', 'TO-104W', 'Концентрат никель-пирротиновый', 'Концентрат никель-пирротиновый ТОФ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (64, '1013059', '0101', '0101-TOF0', 'TO-104W', 'Хвосты породные сгущенные', 'Хвосты отвальные ТОФ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (65, '1040001', '0101', '0101-TOF0', 'TO-104W', 'Концентрат дофлотации малоникелистого пирротина', 'Концентрат дофлотации малоникелистого пирротина', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (66, '9999901', '0101', '0101-TOF0', 'TO-104W', 'Потери ТОФ', 'Потери ТОФ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (67, '907456', '0101', '0101-MEDN', 'BN-102W', 'Бисульфит натрия технический', 'Бисульфит натрия', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (68, '1040003', '0101', '0101-TOF0', 'TO-104W', 'Материал пруда-накопителя', 'Материал пруда-накопителя', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (69, '1002002', '4900', '4900-NOBF', 'IF-301W', 'Концентрат медный', 'Концентрат медный НОФ', '301W', 'IF', 'R', 'да', 'нет', NULL, 'Готовая продукция', 'МР', 1, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (70, '1013053', '0101', '0101-MEDN', 'SM-102W', 'Пульпа объединенная', 'Пульпа объединенная', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (71, '1013177', '0101', '0101-NMZK', 'GN-105W', 'Концентрат медный НМЗ', 'Концентрат медный ГМП', NULL, NULL, 'R', 'нет', NULL, NULL, 'Возвратные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (72, '1013056', '0101', '0101-MEDN', 'TF-102W', 'Концентрат медный отфильтрован.', 'Концентрат медный отфильтрованный', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (73, '1013052', '0101', '0101-MEDN', 'TF-102W', 'Концентрат медный отстойников 3 4', 'Слив сгустителей УФМК в отст. № 3,4', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (74, '9999902', '0101', '0101-MEDN', 'TF-102W', 'Потери УФМК', 'Потери УФМК', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (75, '1013124', '0101', '0101-MEDN', 'SM-102W', 'Концентрат медный ПООФ подсушенный', 'Концентрат медный подсушенный', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (76, '9999903', '0101', '0101-MEDN', 'SM-102W', 'Потери СУ', 'Потери СУ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (77, '6666601', '0102', '0102-2000', NULL, 'Зачистки ОРиД АО "КГМК"', 'Зачистки ОРиД АО "КГМК"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (78, '1000186', '0102', '0102-2000', NULL, 'Медь цементная', 'Медь цементная АО "КГМК"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (79, '6666602', '0102', '0102-2000', NULL, 'Штейн медный АО "КГМК"', 'Штейн медный АО "КГМК"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (80, '3058786', '0101', NULL, NULL, 'Песок технологический', 'Песок', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (81, '1013132', '0101', '0101-MEDN', 'GO-102W', 'КЕК УФП ОМГО', 'КЕК УФП ОМГО', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (82, '1013129', '0101', '0101-MEDN', 'KM-102W', 'Шлак конвертерный жидкий', 'Шлак конвертерный жидкий', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (83, '5555501', '0101', NULL, NULL, 'Медный кек "Харьявалта"', 'Кек медный "Харьявалта"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (84, '1013155', '0101', NULL, NULL, 'Продукты возвратные', 'Возвратные промпродукты ОАО "КЗЦМ"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (85, '1010387', '0101', '0101-MEDN', 'PM-102W', 'Штейн', 'Штейн ПВ', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (86, '1013122', '0101', '0101-MEDN', 'PM-102W', 'Шлак отвальный МЗ', 'Шлак отвальный МЗ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (87, '1013125', '0101', '0101-MEDN', 'PM-102W', 'Обороты бедные (корки)', 'Обороты бедные МЗ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (88, '8888801', '0101', '0101-MEDN', 'PM-102W', 'Газы ПВ', 'Газы ПВ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (89, '9999904', '0101', '0101-MEDN', 'PM-102W', 'Потери ПВ', 'Потери ПВ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (90, '8888802', '0101', '0101-MEDN', 'GO-102W', 'Газы очищенные МГО', 'Газы очищенные МГО', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (91, '1020001', '0101', '0101-MEDN', 'RM-102W', 'Воды промышленные ЦЭМ, (промстоки)', 'Воды промышленные ЦЭМ, (промстоки)', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (92, '1020002', '0101', '0101-MEDN', 'PR-102W', 'Кек ОС +фильтрат ОС', 'Кек ОС +фильтрат ОС', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (93, '1013114', '0101', '0101-MEDN', 'SB-102W', 'Сера техническая жидкая МЗ', 'Сера техническая жидкая МЗ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (94, '373015', '0101', '0101-MEDN', 'KA-102W', 'Лом изложницы из меди анодной', 'Лом изложниц медных МЦ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (95, '1001001', '0101', NULL, NULL, 'Концентрат гравитационный золотосодерж.', 'Концентрат золотосодержащий ООО "ГРКБ"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (96, '1013080', '0101', '0101-MEDN', 'RM-102W', 'Губка медная ЦЭМ МЗ', 'Губка медная ЦЭМ', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (97, '1013085', '0101', '0101-MEDN', 'KA-102W', 'Шлак вторичный МЦ', 'Шлак вторичный МЦ', NULL, NULL, 'R', 'нет', NULL, NULL, 'Возвратные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (98, '1013128', '0101', '0101-MEDN', 'AM-102W', 'Шлак анодный', 'Шлак анодный', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (99, '1050001', '0101', '0101-NMZK', 'CN-105W', 'Лом горловин с НМЗ', 'Лом горловин с НМЗ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (100, '10038537', '0101', NULL, NULL, 'Кварцит', 'Кварцит', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (101, '1013106', '0101', '0101-MEDN', 'KM-102W', 'Медь черновая', 'Медь черновая', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (102, '1013118', '0101', '0101-MEDN', 'KM-102W', 'Шлак никелевый МЗ', 'Шлак никелевый МЗ', NULL, NULL, 'R', 'нет', NULL, NULL, 'Возвратные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (103, '9999905', '0101', '0101-MEDN', 'KM-102W', 'Потери конвертирования', 'Потери конвертирования', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (104, '1013130', '0101', '0101-MEDN', 'RM-102W', 'Скрап медный анодный', 'Скрап медный анодный', NULL, NULL, 'R', 'нет', 'да', 'Cu', 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (105, '1013141', '0101', '0101-MEDN', 'RM-102W', 'Отходы основы ЦЭМ', 'Отходы ЦЭМ', NULL, NULL, 'R', 'нет', 'да', 'Cu', 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (106, '1013079', '0101', '0101-MEDN', 'RM-102W', 'Медь регенерации из ЦЭМ', 'Медь регенерации ЦЭМ ', NULL, NULL, 'R', 'нет', 'да', 'Cu', 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (107, '1013078', '0101', '0101-MEDN', 'AM-102W', 'Анод медный', 'Медь анодная', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (108, '3031806', '0101', '0101-MEDN', 'AM-102W', 'Изделие медное', 'Медные изделия на НМЗ (горловины)', NULL, NULL, 'R', 'нет', NULL, NULL, 'Материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (109, '3031805', '0101', '0101-MEDN', 'AM-102W', 'Изложницы медные', 'Изложницы медные для МЦ', NULL, NULL, 'R', 'нет', NULL, NULL, 'Материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (110, '9999906', '0101', '0101-MEDN', 'AM-102W', 'Потери рафинирования', 'Потери рафинирования', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (111, '1013102', '0101', '0101-MEDN', 'RM-102W', 'Катоды медные', 'Медь катодная', '102W', 'RM', 'R', 'да', 'да', 'Cu', 'Готовая продукция', 'Общий', 1, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (112, '1013081', '0101', '0101-MEDN', 'RM-102W', 'Катоды медные брак. из ЦЭМ', 'Катоды медные бракованные', NULL, NULL, 'R', 'нет', 'да', 'Cu', 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (113, '1013084', '0101', '0101-MEDN', 'RM-102W', 'Шлам медный из ЦЭМ МЗ', 'Шлам медный', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (114, '1013098', '0101', '0101-MEDN', 'RM-102W', 'Раствор обезмеженный', 'Раствор обезмеженный', NULL, NULL, 'R', 'нет', NULL, NULL, 'Возвратные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (115, '1013090', '0101', '0101-MEDN', 'KP-102W', 'Фракция промывки скрапа', 'Фракция промывки скрапа', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (116, '1013089', '0101', '0101-MEDN', 'KP-102W', 'Скрап анодов вторичных', 'Скрап анодов вторичных', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (117, '1013091', '0101', '0101-MEDN', 'KP-102W', 'Раствор выщелачивания огарка', 'Раствор выщелачивания огарка', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (118, '1013088', '0101', '0101-MEDN', 'KA-102W', 'Анод вторичный', 'Аноды вторичные', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (119, '1013093', '0101', '0101-MEDN', 'KA-102W', 'Хлорид серебра отфильтрованный', 'Хлорид серебра отфильтрованный', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (120, '1013061', '0101', '0101-MEDN', 'KA-102W', 'Раствор медно-никелевый МЦ', 'Раствор медно-никелевый МЦ', NULL, NULL, 'R', 'нет', NULL, NULL, 'Возвратные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (121, '1013094', '0101', '0101-MEDN', 'KA-102W', 'Кек осаждения ДМ', 'Кек осаждения ДМ', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (122, '9999907', '0101', '0101-MEDN', 'KA-102W', 'Потери МПГ в анодах', 'Потери МПГ в анодах', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (123, '1013099', '0101', '0101-MEDN', 'AG-102W', 'Раствор перераб. хлорида серебра', 'Раствор переработки хлорида серебра', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (124, '1013134', '0101', '0101-MEDN', 'KP-102W', 'Концентрат платиновых металлов марки ОК', 'КП', '102W', 'KP', 'R', 'да', 'нет', NULL, 'Полуфабрикаты ', 'Общий', 1, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (125, '1013095', '0101', '0101-MEDN', 'KP-102W', 'Раствор ВАР медно-никелевый', 'Раствор ВАР медно-никелевый', NULL, NULL, 'R', 'нет', NULL, NULL, 'Возвратные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (126, '9999908', '0101', '0101-MEDN', 'KP-102W', 'Потери МПГ в КП', 'Потери МПГ в КП', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (127, '1013115', '0101', '0101-MEDN', 'AG-102W', 'Серебро черновое в порошке', 'Серебро черновое в порошке', '102W', 'AG', 'R', 'да', 'да', 'Ag', NULL, 'Общий', 1, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (128, '9999909', '0101', '0101-MEDN', 'AG-102W', 'Потери СПЧ', 'Потери СПЧ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (129, '7777701', '0101', '0101-MEDN', 'GO-102W', 'Сера в газах на производство бисульфита', 'Сера в газах на производство бисульфита', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (130, '7777702', '0101', '0101-MEDN', 'GO-102W', 'Сера в газах на производство кислоты', 'Сера в газах на производство кислоты', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (131, '1013121', '0101', '0101-MEDN', 'SA-102W', 'Кислота серная техническая', 'Кислота серная', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (132, '1020004', '0101', '0101-MEDN', 'GO-102W', 'Стоки ОМГО', 'Стоки ОМГО', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (133, '9999910', '0101', '0101-MEDN', 'SB-102W', 'Потери УПЭС', 'Потери УПЭС', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (134, '9999911', '0101', '0101-MEDN', 'RM-102W', 'Потери ЦЭМ', 'Потери ЦЭМ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (135, '1010372', '0101', '0101-NMZK', 'CN-105W', 'Обороты бедные', 'Обороты бедные конвертерные', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (136, '5555502', '0101', NULL, NULL, 'Концентрат никелевый отстойников "Северный"+"Восточный"', 'Концентрат никелевый отстойников "Северный", "Восточный"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (137, '1013176', '0101', '0101-NMZK', 'GN-105W', 'Концентрат никелевый НМЗ', 'Концентрат никелевый ГМП', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (138, '1013067', '0101', '0101-NMZK', 'GN-105W', 'Концентрат сульфидный', 'Концентрат сульфидный', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (139, '079011', '0101', '0101-NMZK', 'GN-105W', 'Сера комовая', 'Сера элементарная', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (140, '1010375', '0101', '0101-NMZK', 'GN-105W', 'Хвосты отвальные ГМП НМЗ', 'Хвосты отвальные ГМП', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (141, '1050002', '0101', '0101-NMZK', 'GN-105W', 'Сливы ГМП', 'Сливы ГМП', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (142, '1002003', '4900', '4900-NOBF', 'IF-301W', 'Концентрат никелевый', 'Концентрат никелевый НОФ', '301W', 'IF', 'R', 'да', 'нет', NULL, 'Готовая продукция', 'МР', 1, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (143, '326497', '0101', NULL, NULL, 'Осадок м/с т/м Барьерное', 'Осадки металлосодержащие ТМ "Барьерное"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (144, '1013068', '0101', '0101-NMZK', 'SN-105W', 'Концентрат никель-сульфидный', 'СНСК', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (145, '850438', '0101', '0101-NMZK', 'SN-105W', 'Слив сгущения НМЗ', 'СНСК в хранилище', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (146, '16166108', '0101', NULL, NULL, 'Концентрат месторождения "Квадратное"', 'Концентрат ТМ "Квадратное"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (147, '1013075', '0101', '0101-NMZK', 'CN-105W', 'Пыль никелевая конвертерная', 'Пыль никелевая конвертерная', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (148, '798059', '0101', NULL, NULL, 'Песок речной', 'Песок кварцевый', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (149, '1013069', '0101', '0101-NMZK', 'PN-105W', 'Штейн никелевый ПВП', 'Штейн никелевый ПВП', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (150, '1013070', '0101', '0101-NMZK', 'PN-105W', 'Шлак никелевый ПВП', 'Шлак никелевый ПВП', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (151, '9999912', '0101', '0101-NMZK', 'PN-105W', 'Потери ПВП', 'Потери ПВП', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (152, '1013072', '0101', '0101-NMZK', 'CN-105W', 'Шлак никелевый конвертерный', 'Шлак никелевый конвертерный', NULL, NULL, 'R', 'нет', NULL, NULL, 'Оборотные материалы', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (153, '1000192', '0102', '0102-2000', NULL, 'Фракция немагнитная порошка никелевого', 'Немагнитная фракция АО "КГМК"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (154, '1000196', '0102', '0102-2000', NULL, 'Выломки металлургических агрегатов ХМЦ', 'Выломки металлургических агрегатов АО "КГМК"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (155, '10820767', '0101', NULL, NULL, 'Порода вскрышная', 'Порода вскрышная', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (156, '1013071', '0101', '0101-NMZK', 'ON-105W', 'Штейн ОЭП', 'Штейн ОЭП', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (157, '1010377', '0101', '0101-NMZK', 'ON-105W', 'Шлак отвальный ОЭП', 'Шлак отвальный ОЭП', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (158, '1000191', '0102', '0102-2000', NULL, 'Окатыши', 'Окатыши остатков дожигание АО "КГМК"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (159, '1000193', '0102', '0102-2000', NULL, 'Шлак анодный никелевый', 'Шлак анодный никелевый АО "КГМК"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (160, '1000187', '0102', '0102-2000', NULL, 'Пыль РЦ', 'Пыль РЦ АО "КГМК"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (161, '9999913', '0101', '0101-NMZK', 'GN-105W', 'Потери ГМП', 'Потери ГМП', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (162, '8888803', '0101', '0101-NMZK', 'PN-105W', 'Газ технологический ПВП', 'Газ технологический ПВП', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (163, '8888804', '0101', '0101-NMZK', 'ON-105W', 'Газ технологический ОЭП', 'Газ технологический ОЭП', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (164, '9999914', '0101', '0101-NMZK', 'ON-105W', 'Потери ОЭП', 'Потери ОЭП', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (165, '8888805', '0101', '0101-NMZK', 'CN-105W', 'Газ технологический конвертирования никелевых штейнов', 'Газ технологический конвертирования никелевых штейнов', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (166, '9999915', '0101', '0101-NMZK', 'CN-105W', 'Потери конвертирования никелевых штейнов', 'Потери конвертирования никелевых штейнов', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (167, '1050011', '0101', '0101-NMZK', 'PS-105W', 'Пульпа шлака никелевого МЗ', 'Пульпа шлака никелевого МЗ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (168, '1090001', '0101', '0101-NMZK', 'PS-105W', 'Руда богатая р.Таймырский подсушенная', 'Руда богатая р.Таймырский дробленая', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты ', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (169, '10800001', '0101', '0101-NMZK', 'PS-105W', 'Порода вскрышная дробленая', 'Порода вскрышная дробленая', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (170, '1013191', '0101', '0101-NMZK', 'PS-105W', 'Обороты бедные измельченные', 'Обороты бедные дробленые', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (171, '1050010', '0101', '0101-NMZK', 'PS-105W', 'Шлак никелевый дробленый', 'Шлак никелевый дробленый', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (172, '1050003', '0101', '0101-NMZK', 'GN-105W', 'Сера НМЗ', 'Сера НМЗ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (173, '1013073', '0101', '0101-NMZK', 'CN-105W', 'Файнштейн медно-никелевый', 'Файнштейн медно-никелевый', '105W', 'CN', 'R', 'да', 'нет', NULL, NULL, 'ЗФ', 1, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (174, '1002006', '4900', '4900-RZAP', 'D1-302W', 'Руда вкрапленная карьера р. Заполярный', 'Руда вкрапленная карьера р.Заполярный', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (175, '1002007', '4900', '4900-RZAP', 'DR-302W', 'Руда вкрапленная шахты р. Заполярный', 'Руда вкрапленная шахты р.Заполярный ', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (176, '1013193', '4900', '4900-RZAP', 'D1-302W', 'Руда малосульфидная (труднообогатимая)', 'Руда малосульфидная р.Заполярный', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (177, '3020001', '4900', '4900-RZAP', 'D1-302W', 'Руда вкрапленная карьера р. Заполярный (со склада)', 'Руда вкрапленная карьера р. Заполярный (со склада)', NULL, NULL, 'R', 'нет', NULL, NULL, 'Полуфабрикаты', NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (178, '710851', '4900', '4900-NOBF', 'IF-301W', 'Хвосты отвальные НОФ', 'Хвосты отвальные НОФ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (179, '9999916', '4900', '4900-NOBF', 'IF-301W', 'Потери НОФ', 'Потери НОФ', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (180, '1020005', '0102', '0102-2000', NULL, 'Концентрат медный ОРФ АО "КГМК"', 'Концентрат медный ОРФ АО "КГМК"', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (181, '9999920', '0101', '0101-MEDN', 'PR-102W', 'Потери УПР', 'Потери УПР', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);
INSERT INTO public.products_spr (id, product_code, business_org_code, production_unit_code, redev_code, product_name_sap, node_name, zavod_code, redev, node_type, is_cost_product, is_fix_content, fix_component_code, product_type, product_for, coeff_minus, created_at, updated_at, deleted_at) VALUES (182, '5634780', '0101', NULL, NULL, 'Технологические матариалы', 'Технологические матариалы', NULL, NULL, 'R', 'нет', NULL, NULL, NULL, NULL, NULL, '2022-10-18 12:51:56', '2022-10-18 12:51:56', NULL);


--
-- TOC entry 3666 (class 0 OID 0)
-- Dependencies: 245
-- Name: products_spr_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_spr_id_seq', 182, true);


-- Completed on 2022-10-18 16:11:46 MSK

--
-- PostgreSQL database dump complete
--

